name: Update yarn dependencies

# PROBLEM: after I merge a version-updated PR, the yarn.lock file is not updated
# this means the CI build fails in commit to main (for `publich.yml`) during the yarn install step
# I would expect the ci build to not fail because running `yarn` should automatically fix the deps
# Anyway, I'm making the dep upgrade explicit with this workflow

# this workflow updates the yarn deps whenever the GH actions bot
# pushes the new versions to the `changeset-release/main` branch

on:
  push:
    branches:
      - changeset-release/main

jobs:
  update-yarn:
    name: Update Yarn Dependencies and Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Update Deps
        run: yarn

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: Update Yarn dependencies
          committer_name: GitHub Actions
          committer_email: actions@github.com
